version: '3.1'
services:
  wordpress:
    build:
      context: wordpress
    restart: always
    container_name: ${NAME}
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
    volumes:
      - wordpress:/var/www/html
      - ${CONTENT_FOLDER}:/var/www/html/wp-content
      - ./certbot/letsencrypt:/etc/letsencrypt
  db:
    image: mysql:5.7
    restart: always
    container_name: ${NAME}_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    links:
      - "db:database"
  certbot:
    depends_on:
      - wordpress
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${ADMIN_EMAIL} --agree-tos --no-eff-email -d ${HOST}
volumes: 
  wordpress:
  db:
